on:
  workflow_call:
    outputs:
      python_version:
        description: "Used python version for the workflows"
        value: ${{ jobs.load_env.outputs.python_version }}
      pip_version:
        description: "Used pip version for the workflows"
        value: ${{ jobs.load_env.outputs.pip_version }}
      node_version:
        description: "Used node version for the workflows"
        value: ${{ jobs.load_env.outputs.node_version }}

env:
  PYTHON_VERSION: 3.9.13
  NODE_VERSION: 16
  PIP_VERSION: 22.1.2

jobs:
  load_env:
    name: Load environment
    runs-on: ubuntu-latest
    outputs:
      python_version: ${{ steps.load.outputs.python_version }}
      pip_version: ${{ steps.load.outputs.pip_version }}
      node_version: ${{ steps.load.outputs.node_version }}
    steps:
      - name: Load common environment
        id: load
        run: | 
          echo "python_version=${PYTHON_VERSION}" >> $GITHUB_OUTPUT
          echo "pip_version=${PIP_VERSION}" >> $GITHUB_OUTPUT
          echo "node_version=${NODE_VERSION}" >> $GITHUB_OUTPUT